In [8]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [9]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Stressis/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Stressis/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Stressis/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\

In [11]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
#np.random.randn(2,3,5)
#np.ramdom.rand(2,3,5)

#4. Print a.
print(a)


[[[0.19344695 0.85518066 0.40935031 0.41143893 0.89216526]
  [0.12246201 0.88650778 0.61630716 0.35810022 0.87355364]
  [0.26673347 0.42182447 0.72163371 0.64918985 0.18269863]]

 [[0.76184108 0.82850163 0.75857049 0.12993161 0.9703229 ]
  [0.26897718 0.88687418 0.4555253  0.61197428 0.04858939]
  [0.26826224 0.64509845 0.30008153 0.85685363 0.47432335]]]


In [12]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b= np.ones((5,2,3))

#6. Print b.
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size
print("a =",a.size)
b.size
print("b =", b.size)

a = 30
b = 30


In [14]:
#8. Are you able to add a and b? Why or why not?
c= a +b
print(c)
#not the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [19]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a +c
print(d)
# same shapes 

[[[1.19344695 1.85518066 1.40935031 1.41143893 1.89216526]
  [1.12246201 1.88650778 1.61630716 1.35810022 1.87355364]
  [1.26673347 1.42182447 1.72163371 1.64918985 1.18269863]]

 [[1.76184108 1.82850163 1.75857049 1.12993161 1.9703229 ]
  [1.26897718 1.88687418 1.4555253  1.61197428 1.04858939]
  [1.26826224 1.64509845 1.30008153 1.85685363 1.47432335]]]


In [20]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#addition +1

[[[0.19344695 0.85518066 0.40935031 0.41143893 0.89216526]
  [0.12246201 0.88650778 0.61630716 0.35810022 0.87355364]
  [0.26673347 0.42182447 0.72163371 0.64918985 0.18269863]]

 [[0.76184108 0.82850163 0.75857049 0.12993161 0.9703229 ]
  [0.26897718 0.88687418 0.4555253  0.61197428 0.04858939]
  [0.26826224 0.64509845 0.30008153 0.85685363 0.47432335]]]
[[[1.19344695 1.85518066 1.40935031 1.41143893 1.89216526]
  [1.12246201 1.88650778 1.61630716 1.35810022 1.87355364]
  [1.26673347 1.42182447 1.72163371 1.64918985 1.18269863]]

 [[1.76184108 1.82850163 1.75857049 1.12993161 1.9703229 ]
  [1.26897718 1.88687418 1.4555253  1.61197428 1.04858939]
  [1.26826224 1.64509845 1.30008153 1.85685363 1.47432335]]]


In [22]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)
print(a)
##13. Does e equal to a? Why or why not?
# multiple par 1

[[[0.19344695 0.85518066 0.40935031 0.41143893 0.89216526]
  [0.12246201 0.88650778 0.61630716 0.35810022 0.87355364]
  [0.26673347 0.42182447 0.72163371 0.64918985 0.18269863]]

 [[0.76184108 0.82850163 0.75857049 0.12993161 0.9703229 ]
  [0.26897718 0.88687418 0.4555253  0.61197428 0.04858939]
  [0.26826224 0.64509845 0.30008153 0.85685363 0.47432335]]]
[[[0.19344695 0.85518066 0.40935031 0.41143893 0.89216526]
  [0.12246201 0.88650778 0.61630716 0.35810022 0.87355364]
  [0.26673347 0.42182447 0.72163371 0.64918985 0.18269863]]

 [[0.76184108 0.82850163 0.75857049 0.12993161 0.9703229 ]
  [0.26897718 0.88687418 0.4555253  0.61197428 0.04858939]
  [0.26826224 0.64509845 0.30008153 0.85685363 0.47432335]]]


In [23]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [28]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
f[np.where(d<d_mean)] = 25
f[np.where(d>d_mean)] = 75
f[np.where(d==d_min)] = 0
f[np.where(d==d_max)] = 100

print(f)

[[[ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  25. 100.]
  [ 25.  75.  25.  75.   0.]
  [ 25.  75.  25.  75.  25.]]]


In [34]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

f[np.where(d<d_mean)] = 25
f[np.where(d>d_mean)] = 75
f[np.where(d==d_min)] = 0
f[np.where(d==d_max)] = 100

#17. Print d and f. Do you have your expected f?
print(d)
print(f)

[[[1.19344695 1.85518066 1.40935031 1.41143893 1.89216526]
  [1.12246201 1.88650778 1.61630716 1.35810022 1.87355364]
  [1.26673347 1.42182447 1.72163371 1.64918985 1.18269863]]

 [[1.76184108 1.82850163 1.75857049 1.12993161 1.9703229 ]
  [1.26897718 1.88687418 1.4555253  1.61197428 1.04858939]
  [1.26826224 1.64509845 1.30008153 1.85685363 1.47432335]]]
[[[ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  25. 100.]
  [ 25.  75.  25.  75.   0.]
  [ 25.  75.  25.  75.  25.]]]


In [38]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#f = ','.join(f)
f = np.empty((2,3,5), dtype=object)
f[np.where(d<d_mean)] = "B"
f[np.where(d>d_mean)] = "C"
f[np.where(d==d_min)] = "A"
f[np.where(d==d_max)] = "E"
f[np.where(d==d_mean)] = "D"

print(f)

[[['B' 'C' 'B' 'B' 'C']
  ['B' 'C' 'C' 'B' 'C']
  ['B' 'B' 'C' 'C' 'B']]

 [['C' 'C' 'C' 'B' 'E']
  ['B' 'C' 'B' 'C' 'A']
  ['B' 'C' 'B' 'C' 'B']]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
        #[ 'D',  'D',  'B',  'B',  'B'],
        #[ 'D',  'B',  'D',  'D',  'D']],

       #[[ 'B',  'B',  'B',  'B',  'E'],
        #[ 'D',  'D',  'D',  'D',  'D'],
        #[ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.